# This Dockerfile only used for setting up a local Postgres DB for testing
version: "3"

services:
  pocket-http-db:
    # TO DO - change to master once v1 PR merged
    # build: github.com/pokt-foundation/pocket-http-db.git#master
    build: github.com/pokt-foundation/pocket-http-db.git#v1-filter-lbs-by-role
    container_name: pocket-http-db
    restart: always
    ports:
      - 8080:8080
    environment:
      CONNECTION_STRING: postgres://postgres:pgpassword@portal-db:5432/postgres?sslmode=disable # pragma: allowlist secret
      API_KEYS: test_api_key_6789
    depends_on:
      portal-db:
        condition: service_healthy

  portal-db:
    image: pocketfoundation/test-portal-postgres:latest
    container_name: portal-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      retries: 3
